name: news-headline
favicon: null
layout_spectrum: 0.25071
typography_spectrum: 0.73943
title: News Headline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b0b'
    - '#cfd4da'
    - '#413a28'
    - '#9a9486'
    - '#fd3397'
  brandStrength: 0.375
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
