name: dndtalk
favicon: null
layout_spectrum: 0.75215
typography_spectrum: 0.6205
title: dndtalk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1069072145037353
  lightness: 0.5
  saturation: 0.10539580904878676
  rhythmicContrast: 0.5
purpose: []
